[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_SITE_URL = "https://akoramg.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"


